[[testing]]
= Testing

Spring Boot provides a number of utilities and annotations to help when testing your application.

Core test support is provided by the `spring-boot-test` module.
Support for testing auto-configured applications is provided by the `spring-boot-autoconfigure-test` module.
There are also several focused `-test` modules that provide testing support for a particular feature.

Most developers use the `spring-boot-starter-test` starter which supports core and auto-configuration testing as well as JUnit Jupiter, AssertJ, Hamcrest, and a number of other useful libraries,
The focused `-test` modules can then be additionally added when they are applicable to the application.

[TIP]
====
If you have tests that use JUnit 4, JUnit 5's vintage engine can be used to run them.
To use the vintage engine, add a dependency on `junit-vintage-engine`, as shown in the following example:

[source,xml]
----
<dependency>
	<groupId>org.junit.vintage</groupId>
	<artifactId>junit-vintage-engine</artifactId>
	<scope>test</scope>
	<exclusions>
		<exclusion>
			<groupId>org.hamcrest</groupId>
			<artifactId>hamcrest-core</artifactId>
		</exclusion>
	</exclusions>
</dependency>
----
====

`hamcrest-core` is excluded in favor of `org.hamcrest:hamcrest` that is part of `spring-boot-starter-test`.
