antora:
  extensions:
  - require: '/Users/pwebb/projects/antora-xref-extension/packages/antora-xref-extension'
  - require: '/Users/pwebb/projects/antora-zip-contents-collector-extension/packages/zip-contents-collector-extension'
    version_file: gradle.properties
    locations:
    - url: spring-boot-project/spring-boot-actuator-autoconfigure/build/generated/docs/antora-content/spring-boot-actuator-autoconfigure-${version}-${name}-${classifier}.zip
site:
  title: Spring Boot
content:
  sources:
    - url: ./../..
      branches: HEAD
      start_path: spring-boot-project/spring-boot-actuator-autoconfigure/src/docs/antora
      version: 3.3.0-SNAPSHOT
asciidoc:
  sourcemap: true
  attributes:
    page-pagination: ''
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
    chomp: 'all'
  extensions:
    - '@asciidoctor/tabs'
    - '@springio/asciidoctor-extensions'
    - '@springio/asciidoctor-extensions/configuration-properties-extension'
    - '@springio/asciidoctor-extensions/section-ids-extension'
urls:
  latest_version_segment: ''
runtime:
  log:
    failure_level: warn
ui:
  bundle:
    url: /Users/pwebb/projects/antora-ui-spring/build/ui-bundle.zip
