[[yaml]]
= Working With YAML

https://yaml.org[YAML] is a superset of JSON and, as such, is a convenient format for specifying hierarchical configuration data.
The `SpringApplication` class automatically supports YAML as an alternative to properties whenever you have the https://github.com/snakeyaml/snakeyaml[SnakeYAML] library on your classpath.

NOTE: If you use "`Starters`", SnakeYAML is automatically provided by `spring-boot-starter`.



[[yaml.mapping-to-properties]]
== Mapping YAML to Properties
YAML documents need to be converted from their hierarchical format to a flat structure that can be used with the Spring `Environment`.
For example, consider the following YAML document:

[source,yaml,indent=0,subs="verbatim"]
----
	environments:
	  dev:
	    url: "https://dev.example.com"
	    name: "Developer Setup"
	  prod:
	    url: "https://another.example.com"
	    name: "My Cool App"
----

In order to access these properties from the `Environment`, they would be flattened as follows:

[source,properties,indent=0,subs="verbatim"]
----
	environments.dev.url=https://dev.example.com
	environments.dev.name=Developer Setup
	environments.prod.url=https://another.example.com
	environments.prod.name=My Cool App
----

Likewise, YAML lists also need to be flattened.
They are represented as property keys with `[index]` dereferencers.
For example, consider the following YAML:

[source,yaml,indent=0,subs="verbatim"]
----
	 my:
	  servers:
	  - "dev.example.com"
	  - "another.example.com"
----

The preceding example would be transformed into these properties:

[source,properties,indent=0,subs="verbatim"]
----
	my.servers[0]=dev.example.com
	my.servers[1]=another.example.com
----

TIP: Properties that use the `[index]` notation can be bound to Java `List` or `Set` objects using Spring Boot's `Binder` class.
For more details see the "`xref:features/external-config/typesafe-configuration-properties.adoc[Type-safe Configuration Properties]`" section below.

WARNING: YAML files cannot be loaded by using the `@PropertySource` or `@TestPropertySource` annotations.
So, in the case that you need to load values that way, you need to use a properties file.



[[yaml.directly-loading]]
[[yaml.directly-loading]]
== Directly Loading YAML
Spring Framework provides two convenient classes that can be used to load YAML documents.
The `YamlPropertiesFactoryBean` loads YAML as `Properties` and the `YamlMapFactoryBean` loads YAML as a `Map`.

You can also use the `YamlPropertySourceLoader` class if you want to load YAML as a Spring `PropertySource`.



