[[data.nosql.couchbase]]
= Couchbase

https://www.couchbase.com/[Couchbase] is an open-source, distributed, multi-model NoSQL document-oriented database that is optimized for interactive applications.
Spring Boot offers auto-configuration for Couchbase and the abstractions on top of it provided by https://github.com/spring-projects/spring-data-couchbase[Spring Data Couchbase].
There are `spring-boot-starter-data-couchbase` and `spring-boot-starter-data-couchbase-reactive` "`Starters`" for collecting the dependencies in a convenient way.



[[data.nosql.couchbase.connecting]]
== Connecting to Couchbase
You can get a `Cluster` by adding the Couchbase SDK and some configuration.
The `spring.couchbase.*` properties can be used to customize the connection.
Generally, you provide the https://github.com/couchbaselabs/sdk-rfcs/blob/master/rfc/0011-connection-string.md[connection string], username, and password, as shown in the following example:

[source,yaml,indent=0,subs="verbatim",configprops,configblocks]
----
	spring:
	  couchbase:
	    connection-string: "couchbase://192.168.1.123"
	    username: "user"
	    password: "secret"
----

It is also possible to customize some of the `ClusterEnvironment` settings.
For instance, the following configuration changes the timeout to open a new `Bucket` and enables SSL support:

[source,yaml,indent=0,subs="verbatim",configprops,configblocks]
----
	spring:
	  couchbase:
	    env:
	      timeouts:
	        connect: "3s"
	      ssl:
	        key-store: "/location/of/keystore.jks"
	        key-store-password: "secret"
----

TIP: Check the `spring.couchbase.env.*` properties for more details.
To take more control, one or more `ClusterEnvironmentBuilderCustomizer` beans can be used.



[[data.nosql.couchbase.repositories]]
== Spring Data Couchbase Repositories
Spring Data includes repository support for Couchbase.
For complete details of Spring Data Couchbase, see the {spring-data-couchbase-docs}[reference documentation].

You can inject an auto-configured `CouchbaseTemplate` instance as you would with any other Spring Bean, provided a `CouchbaseClientFactory` bean is available.
This happens when a `Cluster` is available, as described above, and a bucket name has been specified:

[source,yaml,indent=0,subs="verbatim",configprops,configblocks]
----
	spring:
	  data:
	    couchbase:
	      bucket-name: "my-bucket"
----

The following examples shows how to inject a `CouchbaseTemplate` bean:

include::code:MyBean[]

There are a few beans that you can define in your own configuration to override those provided by the auto-configuration:

* A `CouchbaseMappingContext` `@Bean` with a name of `couchbaseMappingContext`.
* A `CustomConversions` `@Bean` with a name of `couchbaseCustomConversions`.
* A `CouchbaseTemplate` `@Bean` with a name of `couchbaseTemplate`.

To avoid hard-coding those names in your own config, you can reuse `BeanNames` provided by Spring Data Couchbase.
For instance, you can customize the converters to use, as follows:

include::code:MyCouchbaseConfiguration[]



