antora:
  extensions:
  - '@springio/antora-extensions/partial-build-extension'
  - '@antora/collector-extension'
  - '@antora/atlas-extension'
  - '@opendevise/antora-release-line-extension'
  - '@springio/antora-extensions'
  - require: '@springio/antora-extensions/publish-docsearch-config-extension'
site:
  title: Spring Boot
  url: https://rwinch.github.io/spring-boot/
  robots: allow
git:
  ensure_git_suffix: false
content:
  sources:
  - url: https://github.com/rwinch/spring-boot
    branches: antora
    start_path: spring-boot-project/spring-boot-docs
asciidoc:
  attributes:
    page-pagination: ''
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
    chomp: 'all'
    include-java: 'ROOT:example$docs-src/main/java/org/springframework/boot/docs'
    include-kotlin: 'ROOT:example$docs-src/main/kotlin/org/springframework/boot/docs'
    docs-resources: 'example$docs-src/main/resources'
  extensions:
  - '@asciidoctor/tabs'
  - '@springio/asciidoctor-extensions'
  - '@springio/asciidoctor-extensions/configuration-properties-extension'
  - '@springio/asciidoctor-extensions/section-ids-extension'
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
runtime:
  log:
    failure_level: warn
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/latest/ui-bundle.zip
    snapshot: true
