FROM adoptopenjdk:11-jre-hotspot AS builder
WORKDIR application
ARG JAR=target/*.jar
COPY ${JAR} application.jar
RUN java -Djarmode=tools -jar application.jar extract-layers

FROM adoptopenjdk:11-jre-hotspot
WORKDIR application
COPY --from=builder application/dependencies/ ./
COPY --from=builder application/snapshot-dependencies/ ./
COPY --from=builder application/resources/ ./
COPY --from=builder application/application/ ./
ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]
