#! /bin/bash -eu
[ "$TRACE" == "true" ] && set -x
set -e
set -o pipefail
source /opt/resource/git/common.sh
DEST_DIR="$1"
GIT_DEST_DIR="$(mktemp -d -t git-resource-destination.XXXXXX)"
/opt/resource/git/in "$GIT_DEST_DIR"

PAYLOAD=$(echo /tmp/git-resource-request.*)

ECHO "foo" >> "${DEST_DIR}/foo"
