[[howto.webserver.configure-ssl]]
= Configure SSL

SSL can be configured declaratively by setting the various `+server.ssl.*+` properties, typically in `application.properties` or `application.yml`.
The following example shows setting SSL properties using a Java KeyStore file:

[configprops,yaml]
----
	server:
	  port: 8443
	  ssl:
	    key-store: "classpath:keystore.jks"
	    key-store-password: "secret"
	    key-password: "another-secret"
----

The following example shows setting SSL properties using PEM-encoded certificate and private key files:

[configprops,yaml]
----
	server:
	  port: 8443
	  ssl:
	    certificate: "classpath:my-cert.crt"
	    certificate-private-key: "classpath:my-cert.key"
	    trust-certificate: "classpath:ca-cert.crt"
----

See {spring-boot-module-code}/web/server/Ssl.java[`Ssl`] for details of all of the supported properties.

Using configuration such as the preceding example means the application no longer supports a plain HTTP connector at port 8080.
Spring Boot does not support the configuration of both an HTTP connector and an HTTPS connector through `application.properties`.
If you want to have both, you need to configure one of them programmatically.
We recommend using `application.properties` to configure HTTPS, as the HTTP connector is the easier of the two to configure programmatically.



