[[actuator.metrics.getting-started]]
= Getting started

Spring Boot auto-configures a composite `MeterRegistry` and adds a registry to the composite for each of the supported implementations that it finds on the classpath.
Having a dependency on `micrometer-registry-\{system}` in your runtime classpath is enough for Spring Boot to configure the registry.

Most registries share common features.
For instance, you can disable a particular registry even if the Micrometer registry implementation is on the classpath.
The following example disables Datadog:

[configprops,yaml]
----
	management:
      datadog:
	    metrics:
	      export:
            enabled: false
----

You can also disable all registries unless stated otherwise by the registry-specific property, as the following example shows:

[configprops,yaml]
----
	management:
      defaults:
	    metrics:
	      export:
	        enabled: false
----

Spring Boot also adds any auto-configured registries to the global static composite registry on the `Metrics` class, unless you explicitly tell it not to:

[configprops,yaml]
----
	management:
	  metrics:
	    use-global-registry: false
----

You can register any number of `MeterRegistryCustomizer` beans to further configure the registry, such as applying common tags, before any meters are registered with the registry:

include-code::./commontags/MyMeterRegistryConfiguration[]

You can apply customizations to particular registry implementations by being more specific about the generic type:

include-code::./specifictype/MyMeterRegistryConfiguration[]

Spring Boot also xref:actuator/metrics/supported.adoc[configures built-in instrumentation] that you can control through configuration or dedicated annotation markers.



