resource_types:
  - name: maven-cache-resource
    type: docker-image
    source: {repository: springboot/maven-cache-resource, tag: latest}
resources:
  - name: git-repo
    type: git
    source: &repo-source
      uri: https://github.com/philwebb/spring-boot.git
      branch: maven-restruct
  - name: maven-repo-cache
    type: maven-cache-resource
    source:
      <<: *repo-source
      paths:
        - '**/pom.xml'
jobs:
  - name: cache
    plan:
      - get: git-repo
        trigger: true
      - get: maven-repo-cache
  - name: build
    plan:
      - get: git-repo
        trigger: true
        passed: [cache]
      - get: maven-repo-cache
        passed: [cache]
      - task: run-build
        file: spring-boot/ci/tasks/run-build.yml
