[[features.testing.spring-boot-applications.autoconfigured-spring-data-elasticsearch]]
= Auto-configured Data Elasticsearch Tests
:page-section-summary-toc: 1

You can use `@DataElasticsearchTest` to test Elasticsearch applications.
By default, it configures an `ElasticsearchRestTemplate`, scans for `@Document` classes, and configures Spring Data Elasticsearch repositories.
Regular `@Component` and `@ConfigurationProperties` beans are not scanned when the `@DataElasticsearchTest` annotation is used.
`@EnableConfigurationProperties` can be used to include `@ConfigurationProperties` beans.
(For more about using Elasticsearch with Spring Boot, see "xref:data/nosql/elasticsearch.adoc[Elasticsearch]", earlier in this chapter.)

TIP: A list of the auto-configuration settings that are enabled by `@DataElasticsearchTest` can be xref:test-auto-configuration.adoc[found in the appendix].

The following example shows a typical setup for using Elasticsearch tests in Spring Boot:

include::code:MyDataElasticsearchTests[]



