antora:
  extensions:
  - require: '@opendevise/antora-release-line-extension'
  - require: '@springio/antora-extensions/tabs-migration-extension'
    unwrap_example_block: always
  title: Spring Boot
asciidoc:
  sourcemap: true
  attributes:
    page-pagination: ''
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
    chomp: 'all'
  extensions:
    - '@asciidoctor/tabs'
    - '@springio/asciidoctor-extensions'
    - '@springio/asciidoctor-extensions/configuration-properties-extension'
    - '@springio/asciidoctor-extensions/section-ids-extension'
urls:
  latest_version_segment: ''
runtime:
  log:
    failure_level: warn
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.4.10/ui-bundle.zip
