name: Rebuild Search Index
on:
  workflow_dispatch:
permissions: read-all
jobs:
  build:
    if: github.repository_owner == 'rwinch'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 5
    - id: configure-indexer
      name: Configure Indexer
      uses: spring-io/spring-doc-actions/setup-docsearch-config@main
    - name: Setup INDEX_NAME_TMP
      run: |
        echo "INDEX_NAME_TMP=${{steps.configure-indexer.index-name}}-${GITHUB_RUN_ID}" >> $GITHUB_ENV
        echo ${{ steps.configure-indexer.docsearch-config-path }}
        cat ${{ steps.configure-indexer.docsearch-config-path }}
    - name: Run Indexer
      uses: darrenjennings/algolia-docsearch-action@master
      with:
        algolia_application_id: ${{ secrets.ALGOLIA_APPLICATION_ID }}
        algolia_api_key: ${{ secrets.ALGOLIA_WRITE_KEY }}
        file: ${{ steps.configure-indexer.docsearch-config-path }}
